runtime: python37
instance_class: F4
entrypoint: uwsgi --http-socket :$PORT --wsgi-file server.py --callable app --master --processes 4 --enable-threads
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto